In [1]:
import numpy as np

In [2]:
arr = np.array(np.arange(0,11))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.arange(0,11) # sama aja, np.arange artinya memang array range ...

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Universal functions are basic function that we can apply to every value in array

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr) # exponential, e^...

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

calling random

In [7]:
A = np.random.randn(10) #random normal distributuon
A

array([ 0.43224228,  0.11242997,  1.67243644,  0.17624294,  1.17037028,
        0.69791161,  0.65841225, -1.1280944 , -1.52442763,  0.80632127])

In [9]:
B = np.random.randint(0,10,10) # (low, high, size)
B

array([9, 9, 0, 1, 3, 7, 3, 1, 2, 4])

### Binary Functions

Functions that use 2 arrays

In [10]:
np.add(A,B)

array([ 9.43224228,  9.11242997,  1.67243644,  1.17624294,  4.17037028,
        7.69791161,  3.65841225, -0.1280944 ,  0.47557237,  4.80632127])

In [11]:
C = np.random.randint(0,50,20)
C

array([30, 28, 23,  8, 41, 24,  0,  8, 46, 26, 44,  1, 30, 49, 30, 15,  4,
        3, 37, 24])

In [15]:
np.maximum(A,B)

array([9.        , 9.        , 1.67243644, 1.        , 3.        ,
       7.        , 3.        , 1.        , 2.        , 4.        ])

In [18]:
D = np.random.randn(20)
D

array([ 0.29332381, -0.34449152, -1.17715644, -0.14773205, -0.03240404,
       -1.38788314, -0.95426306, -0.34458522, -0.74410277,  1.21994118,
        0.68794482,  0.52788365,  0.56158171, -1.10354714, -0.54619751,
        0.79000768,  0.99517991, -0.07085467,  0.05563817,  0.39884474])

In [19]:
np.maximum(C,D) # membandingkan maximum values elemen 2 array dengan dimensi yang sama

array([30., 28., 23.,  8., 41., 24.,  0.,  8., 46., 26., 44.,  1., 30.,
       49., 30., 15.,  4.,  3., 37., 24.])

In [20]:
np.max(D)

1.2199411844037191

In [21]:
np.min(C)

0

In [22]:
E = np.random.randint(10,30,20)
E

array([18, 20, 20, 21, 27, 15, 24, 23, 26, 24, 18, 26, 16, 14, 23, 18, 14,
       11, 16, 13])

In [27]:
np.maximum(C,D,E)

UFuncTypeError: Cannot cast ufunc 'maximum' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [28]:
F = np.random.randint(10,30,20)
F

array([22, 20, 26, 13, 13, 11, 19, 11, 24, 25, 28, 25, 15, 17, 16, 26, 25,
       28, 25, 16])

In [29]:
np.maximum(C,E,F) # Kalau mau bandingin lebih dari 2 maka dtype harus sama

array([30, 28, 23, 21, 41, 24, 24, 23, 46, 26, 44, 26, 30, 49, 30, 18, 14,
       11, 37, 24])

In [32]:
web = 'https://numpy.org/doc/stable/reference/ufuncs' # Cek unoversal functions yang lain di web ini

In [33]:
import webbrowser
webbrowser.open(web)

True