### Saving an array

In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('my_array',arr)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

### Saving multiple array 

In [6]:
arr1 = np.load('my_array.npy')
arr1

array([0, 1, 2, 3, 4])

In [7]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# saving them in the zip file
np.savez('zip_array.npz', x=arr1, y=arr2)

In [9]:
archive_array = np.load('zip_array.npz')
archive_array

In [10]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [11]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### save & load as txt file

In [12]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.savetxt('my_txt_arr.txt',arr3,delimiter=',') # Delimiter : Basically what's separating its value

In [14]:
np.loadtxt('my_txt_arr.txt',delimiter=',') # dtype : floating number

array([[1., 2., 3.],
       [4., 5., 6.]])