In [1]:
import numpy as np

In [2]:
# one way of making an array is by converting from a list

In [3]:
my_list1 = [1,2,3,4]

In [4]:
my_array1 = np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2 = [11,22,33,44]

In [7]:
# Combining 2 lists or more
my_lists = [my_list1,my_list2]
print(my_lists)

[[1, 2, 3, 4], [11, 22, 33, 44]]


In [8]:
my_array2 = np.array(my_lists)
print(my_array2)
# Becomes a matrix

[[ 1  2  3  4]
 [11 22 33 44]]


In [10]:
my_array2.shape
# Ngecek ukuran array; 2 baris 4 kolom (baris, kolom)

(2, 4)

In [11]:
my_array2.dtype
# Ngecek data type

dtype('int32')

### Special Case

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros(5).dtype

dtype('float64')

In [16]:
np.zeros(5).shape

(5,)

In [17]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# Bikin dimensi array bisa pake [] maupun ()

In [20]:
np.empty(5)

array([0., 0., 0., 0., 0.])

Identity Matrix

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Make array using the help of arange 

In [22]:
np.arange(5) # (start,stop,step)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(5,30,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])