In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[4]

4

In [4]:
arr2 = np.arange(2,20,2)
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr2[5]

12

In [7]:
arr2[0:3]

array([2, 4, 6])

In [8]:
arr3 = np.arange(10,20)*10
arr3

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [9]:
arr3[0:3] = 100 # replace new value permanently
arr3

array([100, 100, 100, 130, 140, 150, 160, 170, 180, 190])

In [10]:
arr3

array([100, 100, 100, 130, 140, 150, 160, 170, 180, 190])

In [11]:
slice_of_arr3 = arr3[3:]
slice_of_arr3

array([130, 140, 150, 160, 170, 180, 190])

In [12]:
slice_of_arr3[:] = 10 # ngerubah secara permanen juga ke originalnya di arr3
slice_of_arr3

array([10, 10, 10, 10, 10, 10, 10])

In [13]:
arr3

array([100, 100, 100,  10,  10,  10,  10,  10,  10,  10])

### If don't want to be copied, gotta be spesific

In [14]:
arr_copy = arr3.copy()
arr_copy

array([100, 100, 100,  10,  10,  10,  10,  10,  10,  10])

In [21]:
arr_copy.shape[0]

10

In [25]:
arr_copy[:] = 20
arr_copy

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

### Indexing in 2D arrays

In [48]:
arr4 = np.arange(4,6)
arr5 = np.arange(8,10)

arr_2d = np.array(arr5)
arr_2d

array([8, 9])

In [51]:
arr_2d = np.array([arr4,arr5,[12,13]])
arr_2d

array([[ 4,  5],
       [ 8,  9],
       [12, 13]])

In [52]:
arr_2d[1]

array([8, 9])

In [54]:
arr_2d[0]

array([4, 5])

In [56]:
arr_2d[2,1]

13

In [57]:
arr_2d[2][1]

13

### Arrays Slicing 

In [60]:
arr_2d[:,1]

array([ 5,  9, 13])

In [61]:
arr_2d2 = np.array([[10,11,12],[20,21,22],[30,31,32]])
arr_2d2

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [62]:
arr_2d2[:2,1:]

array([[11, 12],
       [21, 22]])

In [63]:
arr_2d2[2]

array([30, 31, 32])

### Fancy Indexing

In [66]:
arr_2d0 = np.zeros((10,8))
arr_2d0

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
arr_length = arr_2d0.shape[0]
arr_length

10

In [69]:
arr_width = arr_2d0.shape[1]
arr_width

8

In [72]:
len(arr_2d0)

10

width(arr_2d0) # lupa kalo width ada atau gak

In [75]:
for i in range(arr_length):
    arr_2d0[i] = i;

In [76]:
arr_2d0

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9.]])

In [83]:
arr_eye0 = np.zeros((5,5))
arr_eye0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
for i in range(arr_eye0.shape[0]):
    arr_eye0[i,i] = i;
    
arr_eye0

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.]])

In [85]:
arr_eye0[[2,3]] # ngambil baris ke 2 & 3

array([[0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.]])

In [86]:
arr_eye0[[4,1]] # ngambil baris ke 4 & 1

array([[0., 0., 0., 0., 4.],
       [0., 1., 0., 0., 0.]])